channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
