type: "LogisticRegression"

encoding:
  requires_encoding: True
  random_state: 123
  cardinality_threshold: 5

outliers:
  flag: True

  log_transform:
    flag: True
    columns: ['lead_time', 'adr']

  outliers_substitute:
    flag: True
    columns: ['total_guests', 'previous_cancellations', 'previous_bookings_not_canceled',
              'booking_changes','required_car_parking_spaces', 'total_of_special_requests', 'total_nights']
    values: [4, 1, 1, 1, 1, 2, 8]

  discretization:
    flag: True
    n_bins: 4
    random_state: 123
    columns: ['agent']